---

- name: "Regenerate grub2 conf handler"
  import_tasks: tasks/RedHat/generic/regenerate-grub2-conf.yml
  when: sap_hana_preconfigure_run_grub2_mkconfig|d(true)

- name: "Reboot handler"
  #fail:
  #  msg: Reboot is required!
  reboot:
  when: sap_hana_preconfigure_fail_if_reboot_required|d(true)

