# Copyright 2021 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

- block:
  - name: install nfs server
    yum:
      name: nfs-utils
  - name: start and enable nfs server
    service:
      name: nfs
      state: started
      enabled: true
  when: ansible_os_family == 'RedHat'

- block:
  - name: install nfs server
    zypper:
      name: nfs-kernel-server
  - name: start and enable nfs server
    service:
      name: nfsserver
      state: started
      enabled: true
  when: ansible_os_family == 'Suse'

- name: ensure export directories exist
  file:
    path: '{{ item.directory }}'
    mode: '{{ item.mode | default(0755) }}'
    owner: '{{ item.owner | default("root") }}'
    group: '{{ item.owner | default("root") }}'
    state: directory
  loop: '{{ nfs_server_exports }}'
  when: item.create | default(true)

- name: configure nfs exports
  template:
    src: etc/exports.j2
    dest: /etc/exports
    owner: root
    group: root
    mode: 0644
  register: configure_nfs_exports

- name: reload nfs exports
  command: exportfs -r
  when: configure_nfs_exports is changed
