- name: SAP NW deploy
  hosts: 127.0.0.1
  connection: local
  roles:
  - role: forminator
    vars:
      sap_state: '{{ state | default("present") }}'
      sap_tf_project_path: './tf'
      sap_hana_backint_install: '{{ sap_hana_backint_bucket_name | default("") != "" }}'
      sap_hana_backint_bucket_name: '{{ sap_hana_backint_bucket_name | default("") }}'
      sap_tf_variables:
        project_id: '{{ sap_project_id }}'
        sap_ascs_instance_name: '{{ sap_ascs_instance_name }}'
        sap_hana_autodelete_boot_disk: '{{ sap_hana_autodelete_boot_disk | default(true) }}'
        sap_hana_boot_disk_size: '{{ sap_hana_boot_disk_size | default(30) }}'
        sap_hana_boot_disk_type: '{{ sap_hana_boot_disk_type | default("pd-ssd") }}'
        sap_hana_create_backup_volume: '{{ sap_hana_create_backup_volume | default(true) }}'
        sap_hana_instance_name: '{{ sap_hana_instance_name }}'
        sap_hana_instance_type: '{{ sap_hana_instance_type | default("n1-highmem-32") }}'
        sap_hana_pd_kms_key: '{{ sap_hana_pd_kms_key | default(None) }}'
        sap_hana_network_tags: '{{ sap_hana_network_tags | default([sap_network_tag | default("sap-allow-all")]) }}'
        sap_hana_service_account_email: '{{ sap_hana_service_account_email | default("{}@{}.iam.gserviceaccount.com".format(sap_hana_service_account_name | default("sap-common-sa"), sap_project_id)) }}'
        sap_nw_additional_disk_type: '{{ sap_nw_additional_disk_type | default("pd-ssd") }}'
        sap_nw_autodelete_boot_disk: '{{ sap_nw_autodelete_boot_disk | default(true) }}'
        sap_nw_boot_disk_size: '{{ sap_nw_boot_disk_size | default(30) }}'
        sap_nw_boot_disk_type: '{{ sap_nw_boot_disk_type | default("pd-ssd") }}'
        sap_nw_instance_type: '{{ sap_nw_instance_type | default("n1-standard-8") }}'
        sap_nw_network_tags: '{{ sap_nw_network_tags | default([sap_network_tag | default("sap-allow-all")]) }}'
        sap_nw_service_account_email: '{{ sap_nw_service_account_email | default("{}@{}.iam.gserviceaccount.com".format(sap_nw_service_account_name | default("sap-common-sa"), sap_project_id)) }}'
        sap_nw_sapmnt_disk_size: '{{ sap_nw_sapmnt_disk_size | default(50) }}'
        sap_nw_swap_disk_size: '{{ sap_nw_swap_disk_size | default(28) }}'
        sap_nw_usrsap_disk_size: '{{ sap_nw_usrsap_disk_size | default(50) }}'
        sap_nw_use_public_ip: '{{ sap_nw_use_public_ip | default(false) }}'
        sap_pas_instance_name: '{{ sap_pas_instance_name }}'
        source_image_family: '{{ sap_source_image_family }}'
        source_image_project: '{{ sap_source_image_project }}'
        subnetwork_nw: '{{ sap_nw_subnetwork }}'
        subnetwork_hana: '{{ sap_hana_subnetwork }}'
        subnetwork_project: '{{ sap_subnetwork_project_id | default("") }}'
        zone: '{{ sap_zone }}'
  tags: [hana, ascs, pas, nw, assertions]

- name: SAP HANA configure
  hosts: hana
  become: yes
  roles:
  - role: sap-hana-scaleup
    vars:
      sap_hana_backint_install: '{{ sap_hana_backint_bucket_name | default("") != "" }}'
      sap_hana_backint_bucket_name: '{{ sap_hana_backint_bucket_name | default("") }}'
      sap_hana_shared_size: '{{ terraform.outputs.hana_shared_size.value }}G'
      sap_hana_data_size: '{{ terraform.outputs.hana_data_size.value }}G'
      sap_hana_log_size: '{{ terraform.outputs.hana_log_size.value }}G'
      sap_hana_usr_size: '{{ terraform.outputs.hana_usr_size.value }}G'
      sap_hana_backup_size: '{{ terraform.outputs.hana_backup_size.value - 1 }}G'
  tags: [hana]

- name: SAP NW configure
  hosts: ascs
  become: yes
  roles:
  - role: nw-distributed
    vars:
      sap_nw_ascs_virtual_host: '{{ terraform.outputs.ascs_instance_name.value }}'
  tags: [ascs, nw]

- name: SAP NW configure
  hosts: pas
  become: yes
  roles:
  - role: nw-distributed 
    vars:
      sap_hana_virtual_host: '{{ terraform.outputs.hana_instance_name.value }}'
      sap_nfs_private_ip: '{{ terraform.outputs.nfs_private_ip.value }}'
      sap_nw_ascs_virtual_host: '{{ terraform.outputs.ascs_instance_name.value }}'
      sap_nw_pas_virtual_host: '{{ terraform.outputs.pas_instance_name.value }}'
  tags: [pas, nw]

- name: Run assertions on HANA
  hosts: hana
  become: yes
  tasks:
  - include_role:
      name: sap-hana-scaleup
      tasks_from: assertions
  tags: [hana, assertions]

- name: Run assertions on application servers
  hosts: nodes
  become: yes
  tasks:
  - include_role:
      name: nw-distributed
      tasks_from: assertions
    vars:
      sap_nw_ascs_instance_name: '{{ terraform.outputs.ascs_instance_name.value }}'
      sap_nw_pas_instance_name: '{{ terraform.outputs.pas_instance_name.value }}'
  tags: [nw, assertions]
