# Copyright 2021 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

- name: SAP NW deploy
  hosts: 127.0.0.1
  connection: local
  roles:
  - role: forminator
    vars:
      sap_tf_project_path: './tf'
      sap_state: '{{ state | default("present") }}'
      sap_hana_backint_install: '{{ sap_hana_backint_bucket_name | default("") != "" }}'
      sap_hana_backint_bucket_name: '{{ sap_hana_backint_bucket_name | default("") }}'
      sap_tf_variables:
        ascs_health_check_port: '{{ sap_nw_ascs_health_check_port | default("6666") }}'
        ascs_instance_name: '{{ sap_ascs_instance_name }}'
        ers_instance_name: '{{ sap_ers_instance_name }}'
        ers_health_check_port: '{{ sap_nw_ers_health_check_port | default("6667") }}'
        gce_ssh_user: '{{ sap_ssh_user }}'
        gce_ssh_pub_key_file: '{{ sap_ssh_pub_key }}'
        hana_autodelete_boot_disk: '{{ sap_hana_autodelete_boot_disk | default(true) }}'
        hana_create_backup_volume: '{{ sap_hana_create_backup_volume | default(true) }}'
        hana_boot_disk_size: '{{ sap_hana_boot_disk_size | default(30) }}'
        hana_boot_disk_type: '{{ sap_hana_boot_disk_type | default("pd-ssd") }}'
        hana_instance_name: '{{ sap_hana_instance_name | default("") }}'
        hana_instance_name_primary: '{{ sap_hana_instance_name_primary | default("") }}'
        hana_instance_name_secondary: '{{ sap_hana_instance_name_secondary | default("") }}'
        hana_instance_type: '{{ sap_hana_instance_type | default("n1-highmem-32") }}'
        hana_network_tags: '{{ sap_hana_network_tags | default([sap_network_tag | default("sap-allow-all")]) }}'
        hana_pd_kms_key: '{{ sap_hana_pd_kms_key | default("") }}'
        hana_additional_disk_type: '{{ sap_hana_additional_disk_type | default("pd-ssd") }}'
        hana_service_account_email: '{{ sap_hana_service_account_email | default("{}@{}.iam.gserviceaccount.com".format(sap_hana_service_account_name | default("sap-common-sa"), sap_project_id)) }}'
        nw_autodelete_boot_disk: '{{ sap_nw_autodelete_boot_disk | default(true) }}'
        nw_boot_disk_size: '{{ sap_nw_boot_disk_size | default(30) }}'
        nw_boot_disk_type: '{{ sap_nw_boot_disk_type | default("pd-ssd") }}'
        nw_instance_type: '{{ sap_nw_instance_type | default("n1-standard-8") }}'
        nw_network_tags: '{{ sap_nw_network_tags | default([sap_network_tag | default("sap-allow-all")]) }}'
        nw_service_account_email: '{{ sap_nw_service_account_email | default("{}@{}.iam.gserviceaccount.com".format(sap_nw_service_account_name | default("sap-common-sa"), sap_project_id)) }}'
        nw_swap_disk_size: '{{ sap_nw_swap_disk_size | default(28) }}'
        nw_usrsap_disk_size: '{{ sap_nw_usrsap_disk_size | default(50) }}'
        pas_instance_name: '{{ sap_pas_instance_name }}'
        nw_as_num_instances: '{{ sap_nw_as_num_instances | default(1) }}'
        project_id: '{{ sap_project_id }}'
        source_image_family: '{{ sap_source_image_family }}'
        source_image_project: '{{ sap_source_image_project }}'
        subnetwork_nw: '{{ sap_nw_subnetwork }}'
        subnetwork_hana: '{{ sap_hana_subnetwork }}'
        subnetwork_project: '{{ sap_subnetwork_project_id | default("") }}'
        primary_zone: '{{ sap_primary_zone }}'
        secondary_zone: '{{ sap_secondary_zone }}'
    tags: [hana, nw, assertions]

- name: SAP HANA configure
  hosts: hana
  become: yes
  roles:
  - role: sap-hana-ha
    vars:
      sap_hana_backint_install: '{{ sap_hana_backint_bucket_name | default("") != "" }}'
      sap_hana_backint_bucket_name: '{{ sap_hana_backint_bucket_name | default("") }}'
      sap_hana_primary_instance_name: '{{ terraform.outputs.hana_primary_instance_name.value }}'
      sap_hana_secondary_instance_name: '{{ terraform.outputs.hana_secondary_instance_name.value }}'
      sap_hana_primary_instance_ip: '{{ terraform.outputs.hana_primary_instance_ip.value }}'
      sap_hana_secondary_instance_ip: '{{ terraform.outputs.hana_secondary_instance_ip.value }}'
      sap_hana_vip: '{{ terraform.outputs.hana_ilb_ip.value }}'
      sap_hana_health_check_port: '{{ terraform.outputs.hana_health_check_port.value }}'
      sap_hana_shared_size: '{{ terraform.outputs.hana_shared_size.value }}G'
      sap_hana_data_size: '{{ terraform.outputs.hana_data_size.value }}G'
      sap_hana_log_size: '{{ terraform.outputs.hana_log_size.value }}G'
      sap_hana_usr_size: '{{ terraform.outputs.hana_usr_size.value }}G'
      sap_hana_backup_size: '{{ terraform.outputs.hana_backup_size.value - 1 }}G'
    tags: [hana]

- name: SAP application configure
  hosts: sap
  become: yes
  become_user: root  
  roles:
  - role: netweaver-ha
    vars:
      sap_hana_vip: '{{ terraform.outputs.hana_ilb_ip.value }}'
      sap_nw_ascs_vip: '{{ terraform.outputs.ascs_ilb_ip.value }}'
      sap_nw_ers_vip: '{{ terraform.outputs.ers_ilb_ip.value }}'
      sap_nw_pas_virtual_host: '{{ terraform.outputs.pas_instance_name.value }}'
      sap_nw_ascs_health_check_port: '{{ terraform.outputs.ascs_health_check_port.value }}'
      sap_nw_ers_health_check_port: '{{ terraform.outputs.ers_health_check_port.value }}'
      subnet_cidr: '{{ terraform.outputs.subnet_cidr_nw.value }}'
    tags: [nw]

- name: Run assertions on HANA
  hosts: hana
  become: yes
  tasks:
  - include_role:
      name: sap-hana-ha
      tasks_from: assertions
    vars:
      sap_hana_primary_instance_name: '{{ terraform.outputs.hana_primary_instance_name.value }}'
      sap_hana_secondary_instance_name: '{{ terraform.outputs.hana_secondary_instance_name.value }}'
  tags: [hana, assertions]

- name: Run assertions on application servers
  hosts: sap
  become: yes
  tasks:
  - include_role:
      name: netweaver-ha
      tasks_from: assertions
  tags: [nw, assertions]
