---
# tasks file for sap-preconfigure: configuration

# 05-configure-firewall.yml
- debug:
    msg: "SAP note 2772999 Step 5: Configure the Firewall"

- import_tasks: ../../RedHat/generic/configure-firewall.yml

...
