# Copyright 2021 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

- name: ensure files are executable
  file:
    path: '{{ sap_nw_install_files_dest }}'
    state: directory
    mode: '0755'
    recurse: true

- name: expand inifile.params
  template:
    src: '{{ sap_sapinst_template }}.j2'
    dest: /usr/sap/{{ sap_sapinst_template }}
    mode: '0600'
    owner: root
    group: root

- name: ensure state directory exists
  file:
    path: '{{ sap_sapinst_state_file | dirname }}'
    state: directory

- name: ensure temp directory exists
  file:
    path: '{{ sap_sapinst_tempdir }}'
    state: directory
    mode: '1777'
    owner: root
    group: root
  when: sap_sapinst_tempdir != '/tmp'

- name: stat state file
  stat:
    path: '{{ sap_sapinst_state_file }}'
  register: sap_sapinst_state_file_stat

- name: ensure sapinst group exists with specified gid
  group:
    name: sapinst
    gid: '{{ sap_sapinst_gid }}'

- name: run sapinst for product id {{ sap_product_id }}
  command: >-
    ./sapinst
      SAPINST_INPUT_PARAMETERS_URL=/usr/sap/{{ sap_sapinst_template }}
      SAPINST_EXECUTE_PRODUCT_ID={{ sap_product_id }}
      SAPINST_SKIP_DIALOGS=true
      SAPINST_START_GUISERVER=false
      {{ sap_sapinst_extra_args }}
  args:
    chdir: '{{ sap_sapinst_swpm_path }}'
  environment:
    TMPDIR: '{{ sap_sapinst_tempdir }}'
  # Using `creates` caused `failed_when` to get finicky, so `when` is being used instead.
  when: not (sap_sapinst_state_file_stat.stat.exists | bool)
  register: sap_sapinst_run
  # Running sapinst for DB2 copy (for standby) in interactive mode prompts the user to exit before doing the
  # restore, whereas in unattended mode as is done here, there does not seem to be a parameter to make it exit
  # at that point. This checks for the string 'Start_Instance' in the sapinst output, which indicates that the
  # DB2 installation finished successfully, even though the exit code is nonzero.
  failed_when: >-
    (sap_sapinst_template != 'inifile_dbcopy_db2.params' and sap_sapinst_run.rc != 0) or
    (sap_sapinst_template == 'inifile_dbcopy_db2.params' and 'Start_Instance' not in sap_sapinst_run.stdout)

- name: store ansible state
  copy:
    content: ''
    dest: '{{ sap_sapinst_state_file }}'
