---
# tasks file for sap-preconfigure: configuration

# 02-configuration-changes.yml
- debug:
    msg: "SAP note 2002167 Step 2a: Configure the Firewall"

- import_tasks: ../../RedHat/generic/configure-firewall.yml

- debug:
    msg: "SAP note 2002167 Step 2b: Configure SELinux"

- import_tasks: ../../RedHat/generic/configure-selinux.yml

...
