# Copyright 2021 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

- name: Include copy ssh keys role
  include_role:
    name: sap-hana-copy-ssh-keys

- name: Include storage role
  include_role:
    name: storage
  vars:
    disks: "{{ sap_hana_disks_worker }}"
    logvols: "{{ sap_hana_logvols_worker }}"
    swapon: "{{ sap_hana_swapon | default(false) }}"

- name: Include hana shared and backup mount role
  include_role:
    name: sap-hana-nfs-mount-standby

- name: Include gceStorageClient role
  include_tasks:
    file: gcestorageclient.yml
  vars:
    gce_storage_client_package: gceStorageClient.py

## Keep this temp to over come perms issues when installing Hana
- name: 'Create {{ sap_hana_data_mountpoint }} and {{ sap_hana_log_mountpoint }}'
  file:
    path: '{{ item }}'
    state: directory
    recurse: true
    mode: 0775
  with_items:
    - '{{ sap_hana_data_mountpoint }}'
    - '{{ sap_hana_log_mountpoint }}'
