galaxy_info:
  author: Red Hat SAP Community of Practice
  description: Deploys `SAP HANA` on the given host(s)
  license: GPLv3
  min_ansible_version: 2.5
  platforms:
  - name: EL
    versions: [ 7, 8 ]

  galaxy_tags: [ 'hana', 'rhel', 'sap' ]

dependencies: []
