---

- import_tasks: ev_user.yml
  when:
    - sap_hana_deployment_hana_userid == ''
    - not sap_hana_deployment_apply_license

- import_tasks: ev_group.yml
  when:
    - sap_hana_deployment_hana_groupid == ''
    - not sap_hana_deployment_apply_license

- import_tasks: password_facts.yml
  when: sap_hana_deployment_use_master_password == 'y'

- import_tasks: hana_deploy.yml
  when: not sap_hana_deployment_apply_license

- import_tasks: license.yml
  when: sap_hana_deployment_apply_license