# Copyright 2021 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

sap_is_ascs: false
sap_is_pas: false

sap_nw_ascs_instance_name: '{{
  hostvars.values()
  | selectattr("sap_is_ascs", "defined")
  | selectattr("sap_is_ascs")
  | map(attribute="ansible_hostname")
  | list
  | first
}}'
sap_nw_pas_instance_name: '{{
  hostvars.values()
  | selectattr("sap_is_pas", "defined")
  | selectattr("sap_is_pas")
  | map(attribute="ansible_hostname")
  | list
  | first
}}'
sap_nw_ascs_virtual_host: '{{ sap_nw_ascs_instance_name }}'
sap_nw_pas_virtual_host: '{{ sap_nw_pas_instance_name }}'

nfs_server_exports:
- directory: /sapmnt
  clients: '{{
    hostvars.values()
    | selectattr("sap_is_pas", "defined")
    | selectattr("sap_is_pas")
    | map(attribute="ansible_default_ipv4.address")
    | list
  }}'
- directory: /usr/sap/trans
  clients: '{{
    hostvars.values()
    | selectattr("sap_is_pas", "defined")
    | selectattr("sap_is_pas")
    | map(attribute="ansible_default_ipv4.address")
    | list
  }}'
sap_nw_ascs_private_ip: '{{
  hostvars.values()
  | selectattr("sap_is_ascs", "defined")
  | selectattr("sap_is_ascs")
  | map(attribute="ansible_default_ipv4.address")
  | list
  | first
}}'

sap_hana_backint_bucket_name: ''
sap_hana_backint_install: '{{ sap_hana_backint_bucket_name | length > 0 }}'
sap_hana_password: ''
sap_hana_db_system_password: '{{ sap_hana_password }}'
sap_hana_sidadm_password: '{{ sap_hana_password }}'
sap_hana_user: '{{ sap_hana_sid | lower }}adm'
sap_hana_virtual_host: '{{ sap_hana_instance_name }}'

sap_nw_ascs_instance_number: '00'
sap_nw_pas_instance_number: '00'
sap_nw_install_files_dest: /sapmnt/Software
sap_nw_kernel_files: /sapmnt/Software/Kernel_Files
sap_nw_rdbms_files: /sapmnt/Software/HANA_CLIENT
sap_nw_password: ''
sap_nw_java_admin_password: '{{ sap_nw_password }}'
sap_nw_java_schema_password: '{{ sap_nw_password }}'
sap_nw_master_password: '{{ sap_nw_password }}'
sap_nw_sapadm_password: '{{ sap_nw_password }}'
sap_nw_schema_password: '{{ sap_nw_password }}'
sap_nw_sidadm_password: '{{ sap_nw_password }}'
sap_nw_user: '{{ sap_nw_sid | lower }}adm'
sap_nw_sidadm_uid: 2000
sap_nw_sapadm_uid: 2001
sap_sapsys_gid: 2626

sap_scs_name: '{{ sap_product_vars[sap_nw_product_and_version].scs_name | default("ASCS") }}'

sap_nw_ascs_install_gateway: false
sap_nw_ascs_install_web_dispatcher: false

sap_nw_disks:
- name: swap
  partition_path : swap
- name: usrsap
  partition_path : usrsap
sap_nw_logvols:
  usrsap:
    size: 100%VG
    vol: usrsap
    mountpoint: /usr/sap
sap_nw_swapvols:
  swap:
    size: 100%VG
    vol: swap
sap_nw_disks_ascs: '{{ sap_nw_disks + [{ "name": "sapmnt", "partition_path": "sapmnt" }] }}'
sap_nw_logvols_ascs: '{{ sap_nw_logvols | combine({ "sapmnt": { "size": "100%VG", "vol": "sapmnt", "mountpoint": "/sapmnt" } }) }}'
sap_nw_swapvols_ascs: '{{ sap_nw_swapvols }}'
sap_nw_disks_pas: '{{ sap_nw_disks }}'
sap_nw_logvols_pas: '{{ sap_nw_logvols }}'
sap_nw_swapvols_pas: '{{ sap_nw_swapvols }}'

sap_nw_sapmnt_nfs_mount_src: '{{ sap_nw_ascs_private_ip }}:/sapmnt'
sap_nw_saptrans_nfs_mount_src: '{{ sap_nw_ascs_private_ip }}:/usr/sap/trans'
sap_nw_nfsvols_pas:
- source: '{{ sap_nw_sapmnt_nfs_mount_src }}'
  mountpoint: /sapmnt
- source: '{{ sap_nw_saptrans_nfs_mount_src }}'
  mountpoint: /usr/sap/trans

sap_nw_product: 'NetWeaver'
sap_nw_product_version: '750'
sap_nw_product_and_version: '{{ sap_nw_product }}/{{ sap_nw_product_version }}'
# sap_nw_product and sap_nw_product_version must be set to one of the <product>/<version> combos in sap_product_vars.
sap_product_vars:
  'BW4HANA/20':
    db_product_id: 'NW_ABAP_DB:BW4HANA20.CORE.HDB.ABAP'
    pas_product_id: 'NW_ABAP_CI:BW4HANA20.CORE.HDB.ABAP'
    ascs_product_id: 'NW_ABAP_ASCS:BW4HANA20.CORE.HDB.ABAP'
    swpm_path: /sapmnt/Software/SWPM2.0
    load_files: /sapmnt/Software/Kernel_Files
    install_files: [Kernel_Files, SWPM2.0]
    ensa_version: '2'
  'NetWeaver/750':
    db_product_id: 'NW_ABAP_DB:NW750.HDB.ABAP'
    pas_product_id: 'NW_ABAP_CI:NW750.HDB.ABAP'
    ascs_product_id: 'NW_ABAP_ASCS:NW750.HDB.ABAP'
    swpm_path: /sapmnt/Software/SWPM1.0
    load_files: /sapmnt/Software/NW75
    install_files: [HANA_CLIENT, Kernel_Files, NW75, SWPM1.0]
    ensa_version: '1'
  'NetWeaver/751':
    db_product_id: 'NW_ABAP_DB:NW751.HDB.ABAP'
    pas_product_id: 'NW_ABAP_CI:NW751.HDB.ABAP'
    ascs_product_id: 'NW_ABAP_ASCS:NW751.HDB.ABAP'
    swpm_path: /sapmnt/Software/SWPM1.0
    load_files: /sapmnt/Software/NW75
    install_files: [HANA_CLIENT, Kernel_Files, NW75, SWPM1.0]
    ensa_version: '1'
  'NetWeaver/752':
    db_product_id: 'NW_ABAP_DB:NW752.HDB.ABAP'
    pas_product_id: 'NW_ABAP_CI:NW752.HDB.ABAP'
    ascs_product_id: 'NW_ABAP_ASCS:NW752.HDB.ABAP'
    swpm_path: /sapmnt/Software/SWPM1.0
    load_files: /sapmnt/Software/NW75
    install_files: [HANA_CLIENT, Kernel_Files, NW75, SWPM1.0]
    ensa_version: '1'
  'NetWeaver-Java/750':
    db_product_id: 'NW_Java_DB:NW750.HDB.PD'
    pas_product_id: 'NW_Java_CI:NW750.HDB.PD'
    ascs_product_id: 'NW_Java_SCS:NW750.HDB.PD'
    swpm_path: /sapmnt/Software/SWPM10SP32
    load_files: /sapmnt/Software/NW75
    install_files: [HANA_CLIENT, Kernel_Files, NW75, SWPM10SP32]
    ensa_version: '1'
    scs_name: 'SCS'
    db_sapinst_template: inifile_db_java_hdb.params
    as_sapinst_template: inifile_as_java_hdb.params
  'S4HANA/1709':
    db_product_id: 'NW_ABAP_DB:S4HANA1709.CORE.HDB.ABAP'
    pas_product_id: 'NW_ABAP_CI:S4HANA1709.CORE.HDB.ABAP'
    ascs_product_id: 'NW_ABAP_ASCS:S4HANA1709.CORE.HDB.ABAP'
    swpm_path: /sapmnt/Software/SWPM1.0
    load_files: /sapmnt/Software/S4HANA_Export
    install_files: [HANA_CLIENT, Kernel_Files, S4HANA_Export, SWPM1.0]
    ensa_version: '1'
  'S4HANA/1809':
    db_product_id: 'NW_ABAP_DB:S4HANA1809.CORE.HDB.ABAP'
    pas_product_id: 'NW_ABAP_CI:S4HANA1809.CORE.HDB.ABAP'
    ascs_product_id: 'NW_ABAP_ASCS:S4HANA1809.CORE.HDB.ABAP'
    swpm_path: /sapmnt/Software/SWPM2.0
    load_files: /sapmnt/Software/Kernel_Files
    install_files: [Kernel_Files, SWPM2.0]
    ensa_version: '2'
  'S4HANA/1909':
    db_product_id: 'NW_ABAP_DB:S4HANA1909.CORE.HDB.ABAP'
    pas_product_id: 'NW_ABAP_CI:S4HANA1909.CORE.HDB.ABAP'
    ascs_product_id: 'NW_ABAP_ASCS:S4HANA1909.CORE.HDB.ABAP'
    swpm_path: /sapmnt/Software/SWPM2.0
    load_files: /sapmnt/Software/Kernel_Files
    install_files: [Kernel_Files, SWPM2.0]
    ensa_version: '2'
  'S4HANA/2020':
    db_product_id: 'NW_ABAP_DB:S4HANA2020.CORE.HDB.ABAP'
    pas_product_id: 'NW_ABAP_CI:S4HANA2020.CORE.HDB.ABAP'
    ascs_product_id: 'NW_ABAP_ASCS:S4HANA2020.CORE.HDB.ABAP'
    swpm_path: /sapmnt/Software/SWPM2.0
    load_files: /sapmnt/Software/Kernel_Files
    install_files: [Kernel_Files, SWPM2.0]
    ensa_version: '2'
