---

- debug:
    msg: "imported RedHat/generic/disable-thp.yml"

# can be configured by tuned profile sap-hana, entry "transparent_hugepages=never"
- block:
    - name: Disable transparent hugepages at boot time
      lineinfile:
        path: /etc/default/grub
        backup: yes
        backrefs: yes
        state: present
        regexp: '^(GRUB_CMDLINE_LINUX=(?!.* {{ line_item }}).*). *$'
        line: "\\1 {{ line_item }}\""
      with_items:
         - "transparent_hugepage=never"
      notify: "Regenerate grub2 conf handler"
      when:
        - ansible_os_family == 'RedHat'
        - sap_hana_preconfigure_modify_grub_cmdline_linux
      tags: grubconfig
      loop_control:
        loop_var: line_item

  when:
    - not sap_hana_preconfigure_use_tuned_where_possible

...
