# Copyright 2021 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

- name: ensure that a known product version is defined for db2
  assert:
    that: sap_db2_product_and_version in sap_product_vars
    fail_msg: 'sap_db2_product and sap_db2_product_version must match one of {{ sap_product_vars.keys() | select("match", "^{}/".format(sap_db2_product)) | list | join(", ") }}'
  run_once: true

- name: ensure that a known product version is defined for sap
  assert:
    that: sap_nw_product_and_version in sap_product_vars
    fail_msg: 'sap_nw_product and sap_nw_product_version must match one of {{ sap_product_vars.keys() | select("match", "^{}/".format(sap_nw_product)) | list | join(", ") }}'
  run_once: true

- name: include base role
  include_role:
    name: base

- name: include hosts-file role
  include_role:
    name: hosts-file
  vars:
    hosts_file_peers: '{{ ansible_play_hosts }}'

- name: include ascs tasks
  include_tasks: '{{ role_path }}/tasks/ascs.yml'
  when: sap_is_ascs | bool

- name: include ers tasks
  include_tasks: '{{ role_path }}/tasks/ers.yml'
  when: sap_is_ers | bool

- name: include pacemaker role
  include_role:
    name: pacemaker-netweaver
  vars:
    sap_cluster_user_password: '{{ sap_nw_cluster_user_password }}'
    sap_ensa_version: '{{ sap_product_vars[sap_nw_product_and_version].ensa_version }}'
    sap_primary_instance: '{{ sap_nw_ascs_instance_name }}'
    sap_primary_instance_ip: '{{ sap_nw_ascs_private_ip }}'
    sap_secondary_instance: '{{ sap_nw_ers_instance_name }}'
  when: sap_is_scs | bool

- name: include db2 tasks
  include_tasks: '{{ role_path }}/tasks/db2.yml'
  when: sap_is_db2 | bool

# Hack to work around the following PAS install failure with DB2 11.x:
# "An error occurred during table depooling: Batch job SWPM_RUTPOADAPT terminated".
- name: include db2-lock-escalation role
  include_role:
    name: db2-lock-escalation
  vars:
    sap_db2_lock_escalation_avoid: false
    sap_db2_lock_escalation_state_file: '{{ sap_db2_state_dir }}/toggle-db2-lock-escalation'
  when: sap_is_db2_primary | bool

- name: include pas tasks
  include_tasks: '{{ role_path }}/tasks/as.yml'
  when: sap_is_pas | bool
  vars:
    sap_product_id: '{{ sap_product_vars[sap_nw_product_and_version].pas_product_id }}'

# Un-hack.
- name: include db2-lock-escalation role
  include_role:
    name: db2-lock-escalation
  vars:
    sap_db2_lock_escalation_avoid: true
    sap_db2_lock_escalation_state_file: '{{ sap_db2_state_dir }}/toggle-db2-lock-escalation'
  when: sap_is_db2_primary | bool

- name: include aas tasks
  include_tasks: '{{ role_path }}/tasks/as.yml'
  when: sap_is_aas | bool
  vars:
    sap_product_id: '{{ sap_product_vars[sap_nw_product_and_version].aas_product_id }}'
