---
# tasks file for sap-preconfigure: configuration

# 06-configure-uuidd.yml
- debug:
    msg: "SAP note 2772999 Step 6: Configure uuidd"

- import_tasks: ../../RedHat/generic/configure-uuidd.yml

...
